routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resources([
    'recalls' => 'RecallController',
    'bids' => 'BidController'
]);

// menu
Route::get('/', 'SiteController@index')->name('index');
Route::get('/bids', 'BidController@index')->name('bids');
Route::get('/recalls', 'RecallController@index')->name('recalls');
Route::get('/jobs', 'JobController@index')->name('job');
Route::get('/contacts', 'ContactController@index')->name('contacts');
Route::get('/items/{item}', 'ItemController@show')->name('item_show');

Route::get('recalls/create', 'RecallController@create');


/**************************************************************************************************/

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout');

//Если нужно разрешить регистрацию других пользователей, тогда нужно ввести флаг для роли админа
Route::any('register', function (){
    return redirect('/');
});


Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function ()
{
    Route::post('items/{item}', 'ItemController@recovery')->name('item_recovery');

    Route::resources([
        'items' => 'ItemController',
        'employees' => 'HumanController',
        'recalls' => 'RecallController'
    ]);

// menu admin
    Route::get('/','SiteController@index');
    Route::get('/bids', 'BidController@index');
    Route::get('/recalls', 'RecallController@index');
    Route::get('/jobs', 'JobController@index');
    Route::get('/contacts', 'ContactController@index');
    Route::get('/emloyees','HumanController@index');
/**************************************************************************************************/

// Item
    Route::get('items/create','ItemController@create');
    Route::get('items/{item}/edit','ItemController@edit');
    Route::put('items/{item}','ItemController@update');
    Route::delete('items/{item}','ItemController@destroy')->name('item_delete');
/**************************************************************************************************/

// Employee
    Route::get('emloyees/create','HumanController@create');
    Route::get('emloyees/{emloyee}/edit','HumanController@edit');
    Route::put('emloyees/{emloyee}','HumanController@update');
    Route::delete('emloyees/{emloyee}','HumanController@destroy');
/**************************************************************************************************/
    // Recall
    Route::get('recalls/create', 'RecallController@create');
    Route::get('recalls/{recall}/edit','RecallController@edit');
    Route::put('recalls/{recall}','RecallController@update');
    Route::delete('recalls/{recall}','RecallController@destroy');

    // Bids
    Route::get('bids/{bid}/edit','BidController@edit');
    Route::put('bids/{bid}','BidController@update');

});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    protected $guarded = [];

    use SoftDeletes;

    public function photos()
    {
        return $this->hasMany('App\Photo');
    }

    public function action()
    {
        return $this->belongsTo('App\Action');
    }

    public function client()
    {
        return $this->belongsTo('App\Human', 'client_id', 'id');
    }

    public function employee()
    {
        return $this->belongsTo('App\Human', 'employee_id', 'id');
    }

    public function quarter()
    {
        return $this->belongsTo('App\Quarter');
    }

    public function region()
    {
        return $this->belongsTo('App\Region');
    }

    public function status()
    {
        return $this->belongsTo('App\Status');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Item;
use App\Action;
use App\Quarter;
use App\Region;
use App\Status;
use App\Human;
use App\Photo;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employees = Human::where('client', 0)->get();
        $actions = Action::all();
        $quarters = Quarter::all();
        $regions = Region::get()->toTree();
        $statuses = Status::all();
        return view('admin.items.create', compact('actions', 'quarters', 'employees','regions', 'statuses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'price' => 'required|integer',
            'address' => 'required|string',
            'square' => 'required|integer',
            'image[]' => 'mimes:jpeg,jpg|dimensions:min_width=800,min_height=800',
            'firstname' => 'required|string',
            'surname' => 'required|string',
            'phone' => 'required|regex:/^0[0-9]{2}\s[0-9]{3}\s[0-9]{2}\s[0-9]{2}$/',
            'client' => 'required|integer'
        ]);
        if($request->isMethod('post'))
        {
            $client = new Human([
                'firstname' => $request->get('firstname'),
                'surname' => $request->get('surname'),
                'phone' => $request->get('phone'),
                'client' => $request->get('client')
            ]);
            $client->save();

            $item = new Item([
                'region_id' => $request->get('region'),
                'quarter_id' => $request->get('quarter'),
                'action_id' => $request->get('action'),
                'status_id' => $request->get('status'),
                'client_id' => $client->id,
                'employee_id' => $request->get('employee'),
                'rooms' => $request->get('rooms'),
                'specification' => $request->get('specification'),
                'price' => $request->get('price'),
                'square' => $request->get('square'),
                'address' => $request->get('address'),
                'floors' => $request->get('floors'),
                'number_floors' => $request->get('number_floors')
            ]);
            $item->save();

            if ($request->hasFile('image')) {
                $item->with_photo = 1;
                $item->save();

                $files = $request->file('image');
                foreach ($files as $file) {
                    $photo = new Photo();

                    $extension = $file->getClientOriginalExtension();
                    $fileName = md5_file($file) . '.' . $extension;

                    $imagePath = '/storage/images/' . $fileName;
                    \Image::make($file)->resize(800, 600)->save( storage_path('app/public/images/' . $fileName) );

                    $photo->src_photo = $imagePath;
                    $photo->item_id = $item->id;
                    $photo->save();
                }
            }
        }
        return redirect('/admin/items/create')->with('message', 'Объект добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        \DB::connection()->enableQueryLog();
        $regions = Region::get()->toTree();
        return view('site.show', compact('item', 'regions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $employees = Human::where('client', 0)->get();
        $actions = Action::all();
        $quarters = Quarter::all();
        $regions = Region::get()->toTree();
        $statuses = Status::all();

        $parent_city = Region::find($item->region_id);
        $item_city = Region::find($parent_city->parent_id);

        return view('admin.items.edit', compact('item', 'actions', 'quarters', 'employees','regions', 'statuses', 'item_city'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $request->validate([
            'price' => 'required|integer',
            'address' => 'required|string',
            'square' => 'required|integer',
            'image[]' => 'mimes:jpeg,jpg|dimensions:min_width=800,min_height=800',
            'firstname' => 'required|string',
            'surname' => 'required|string',
            'phone' => 'required|regex:/^0[0-9]{2}\s[0-9]{3}\s[0-9]{2}\s[0-9]{2}$/',
            'client' => 'required|integer'
        ]);

        $client = Human::find($item->client_id);
        $client->update([
            'firstname' => $request->get('firstname'),
            'surname' => $request->get('surname'),
            'phone' => $request->get('phone'),
            'client' => $request->get('client')
        ]);

        $item->update([
            'region_id' => $request->get('region'),
            'quarter_id' => $request->get('quarter'),
            'action_id' => $request->get('action'),
            'status_id' => $request->get('status'),
            'employee_id' => $request->get('employee'),
            'rooms' => $request->get('rooms'),
            'specification' => $request->get('specification'),
            'price' => $request->get('price'),
            'square' => $request->get('square'),
            'address' => $request->get('address'),
            'floors' => $request->get('floors'),
            'number_floors' => $request->get('number_floors')
        ]);

        if ($request->hasFile('image')) {
            $files = $request->file('image');
            foreach ($files as $file) {
                $photo = new Photo();

                $extension = $file->getClientOriginalExtension();
                $fileName = md5_file($file) . '.' . $extension;

                $imagePath = '/storage/images/' . $fileName;
                \Image::make($file)->resize(800, 600)->save( storage_path('app/public/images/' . $fileName) );

                $photo->src_photo = $imagePath;
                $photo->item_id = $item->id;
                $photo->save();
            }
        }
        return redirect('admin')->with('message', 'Редактирование успешно сохранено!');
    }

    public function recovery($id)
    {
        Item::onlyTrashed()->find($id)->restore();
        return redirect('admin')->with('message', 'Объект восстановлен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
        return redirect('admin')->with('message', 'Объект удален!');
    }
}

resources/views/admin/items/create.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.message')
    <section class="uk-section">
            <form action="{{ route('admin.items.store') }}" method="POST" enctype="multipart/form-data" class="uk-form-horizontal uk-margin-large">
                @csrf
                <h4>Объект</h4>
                <hr>
                <div class="uk-margin">
                    <label for="action" class="uk-form-label">Действие</label>
                    <div class="uk-form-controls">
                        <select id="action" class="uk-select uk-form-width-large" name="action">
                            <option selected disabled>Любое</option>
                            @foreach($actions as $action)
                                <option value="{{$action->id}}">{{ $action->action_name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <city-regions :regions="{{$regions}}"></city-regions>

                    <label for="quarter" class="uk-form-label">Тип недвижимости</label>
                    <div class="uk-form-controls">
                        <select id="quarter" class="uk-select uk-form-width-large" name="quarter">
                            <option selected disabled>Любой</option>
                            @foreach($quarters as $quarter)
                                <option value="{{$quarter->id}}">
                                    {{ $quarter->quarter_name }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <label for="status" class="uk-form-label">Состояние</label>
                    <div class="uk-form-controls">
                        <select id="status" class="uk-select uk-form-width-large" name="status">
                            <option selected disabled>Любое</option>
                            @foreach($statuses as $status)
                                <option value="{{$status->id}}">{{ $status->status_name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <label for="rooms" class="uk-form-label">Количество комнат</label>
                    <div class="uk-form-controls">
                        <input id="rooms" type="number" name="rooms" class="uk-input uk-form-width-large">
                    </div>

                    <label for="number_floors" class="uk-form-label">Этаж</label>
                    <div class="uk-form-controls">
                        <input id="number_floors" type="number" name="number_floors" class="uk-input uk-form-width-large">
                    </div>

                    <label for="floors" class="uk-form-label">Этажность</label>
                    <div class="uk-form-controls">
                        <input id="floors" type="number" name="floors" class="uk-input uk-form-width-large">
                    </div>

                    <label for="price" class="uk-form-label">Цена</label>
                    <div class="uk-form-controls">
                        <input id="price" type="number" name="price" class="uk-input uk-form-width-large">
                    </div>

                    <label for="address" class="uk-form-label">Адресс</label>
                    <div class="uk-form-controls">
                        <input id="address" type="text" name="address" class="uk-input uk-form-width-large" placeholder="ул. Строителей, д. 5, кв. 144">
                    </div>

                    <label for="square" class="uk-form-label">Площадь</label>
                    <div class="uk-form-controls">
                        <input id="square" type="number" name="square" class="uk-input uk-form-width-large">
                    </div>

                    <label for="specification" class="uk-form-label">Описание</label>
                    <div class="uk-form-controls">
                        <textarea id="specification" name="specification" class="uk-textarea uk-form-width-large" rows="5" maxlength="1000" placeholder="Описание"></textarea>
                    </div>
                </div>
                <div class="uk-margin">
                    <div class="uk-margin">
                        <label class="uk-form-label">Фото</label>
                    </div>
                    <div class="uk-form-controls" uk-form-custom="target: true">
                        <input type="file" name="image[]" multiple>
                        <input class="uk-input  uk-form-width-large" type="text" placeholder="Выберите файл(ы)" disabled>
                    </div>
                </div>
                <div class="uk-margin">
                    <h4>Клиент</h4>
                    <hr>
                    <label for="client_firstname" class="uk-form-label">Имя</label>
                    <div class="uk-form-controls">
                        <input id="client_firstname" type="text" name="firstname" class="uk-input uk-form-width-large"><br>
                    </div>
                    <label for="client_surname" class="uk-form-label">Фамилия</label>
                    <div class="uk-form-controls">
                        <input id="client_surname" type="text" name="surname" class="uk-input uk-form-width-large"><br>
                    </div>
                    <label for="client_phone" class="uk-form-label">Телефон</label>
                    <div class="uk-form-controls">
                        <input id="client_phone" type="text" name="phone" class="uk-input uk-form-width-large" placeholder="XXX XXX XX XX"><br>
                    </div>
                    <div hidden>
                        <input type="number" name="client" value="1"><br>
                    </div>
                </div>
                <div class="uk-margin">
                    <h4>Сотрудник</h4>
                    <hr>
                    <label for="employee" class="uk-form-label">Сотрудник:</label>
                    <div class="uk-form-controls">
                        <select id="employee" class="uk-select uk-form-width-large" name="employee">
                            <option selected disabled>Выберите сотрудника</option>
                            @foreach($employees as $employee)
                                <option value="{{$employee->id}}">{{ $employee->firstname . ' ' . $employee->surname }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="uk-margin">
                    <button type="submit" class="uk-button uk-button-primary uk-width-1-1 uk-margin-small-bottom">Добавить</button>
                </div>
            </form>
    </section>
@endsection

resources/views/admin/items/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="uk-section">
        @include('layouts.message')
        <div class="uk-child-width " uk-grid>
            <div class="uk-margin-small-top">
                @if($item->photos->isNotEmpty())
                    <div uk-slideshow="animation: push">
                        <div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1">

                            <ul class="uk-slideshow-items">
                                @foreach($item->photos as $photo)
                                    <li>
                                        <img src="{{ asset($photo->src_photo) }}" alt="Photo" uk-cover>
                                    </li>
                                @endforeach
                            </ul>

                            <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
                            <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>

                        </div>

                        <ul class="uk-slideshow-nav uk-dotnav uk-flex-center uk-margin"></ul>

                    </div>
                @endif
            </div>
            <form action="{{ route('admin.items.update', $item) }}" method="POST" enctype="multipart/form-data" class="uk-form-horizontal uk-margin-large">
                @csrf
                @method('PUT')
                <h4>Объект</h4>
                <hr>
                @if(Auth::check() && $item->deleted == 1)
                    <h3 style="color: red;">Объект удален!</h3>
                @endif
                <div class="uk-margin">
                    <label for="action" class="uk-form-label">Действие</label>
                    <div class="uk-form-controls">
                        <select id="action" class="uk-select uk-form-width-large" name="action">
                            <option selected disabled>Любое</option>
                            @foreach($actions as $action)
                                <option value="{{$action->id}}" {{ $item->action_id == $action->id ? 'selected' : '' }}>{{ $action->action_name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <label for="city" class="uk-form-label">Город</label>
                    <div class="uk-form-controls">
                        <select id="city" class="uk-select uk-form-width-large" name="city">
                            <option disabled selected value="">Любой</option>
                            @foreach($regions as $region)
                                <option value={{$region->id}} {{($region->id == $item_city->id)?'selected':''}} {{($region->disabled == 1)? 'disabled': ''}}>
                                    {{ $region->region_name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <label for="region" class="uk-form-label">Район города</label>
                    <div class="uk-form-controls">
                        <select id="region" class="uk-select uk-form-width-large" name="region">
                            <option disabled selected value="">Любой</option>
                            @foreach($regions as $region)
                                @foreach($region->children as $reg)
                                    <option value={{$reg->id}}  {{($reg->id == $item->region_id)?'selected':''}}>{{ $reg->region_name }}</option>
                                @endforeach
                            @endforeach
                        </select>
                    </div>

                    <label for="quarter" class="uk-form-label">Тип недвижимости</label>
                    <div class="uk-form-controls">
                        <select id="quarter" class="uk-select uk-form-width-large" name="quarter">
                            <option selected disabled>Любой</option>
                            @foreach($quarters as $quarter)
                                <option value="{{$quarter->id}}" {{ $item->quarter_id == $quarter->id ? 'selected' : '' }}>
                                    {{ $quarter->quarter_name }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <label for="status" class="uk-form-label">Состояние</label>
                    <div class="uk-form-controls">
                        <select id="status" class="uk-select uk-form-width-large" name="status">
                            <option selected disabled>Любое</option>
                            @foreach($statuses as $status)
                                <option value="{{$status->id}}" {{ $item->status_id == $status->id ? 'selected' : '' }}>{{ $status->status_name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <label for="rooms" class="uk-form-label">Количество комнат</label>
                    <div class="uk-form-controls">
                        <input id="rooms" type="number" name="rooms" class="uk-input uk-form-width-medium" value="{{ $item->rooms }}">
                    </div>
                    @if($item->number_floors)
                        <label for="number_floors" class="uk-form-label">Этаж</label>
                        <div class="uk-form-controls">
                            <input id="number_floors" type="number" name="number_floors" class="uk-input uk-form-width-medium" value="{{ $item->number_floors }}">
                        </div>
                    @endif
                    @if($item->floors)
                        <label for="floors" class="uk-form-label">Этажность</label>
                        <div class="uk-form-controls">
                            <input id="floors" type="number" name="floors" class="uk-input uk-form-width-medium" value="{{ $item->floors }}">
                        </div>
                    @endif
                    <label for="price" class="uk-form-label">Цена</label>
                    <div class="uk-form-controls">
                        <input id="price" type="number" name="price" class="uk-input uk-form-width-medium" value="{{ $item->price }}">
                    </div>

                    <label for="address" class="uk-form-label">Адресс</label>
                    <div class="uk-form-controls">
                        <input id="address" type="text" name="address" class="uk-input uk-form-width-large" value="{{ $item->address }}">
                    </div>

                    <label for="square" class="uk-form-label">Площадь</label>
                    <div class="uk-form-controls">
                        <input id="square" type="number" name="square" class="uk-input uk-form-width-medium" value="{{ $item->square }}">
                    </div>

                    <label for="specification" class="uk-form-label">Описание</label>
                    <div class="uk-form-controls">
                        <textarea id="specification" name="specification" class="uk-textarea" rows="5" maxlength="1000" placeholder="Описание">{{ $item->specification }}</textarea>
                    </div>
                </div>
                <div class="uk-margin">
                    <div>
                        <label class="uk-form-label">Фото</label>
                    </div>
                    <div uk-form-custom="target: true">
                        <input type="file" name="image[]" multiple>
                        <input class="uk-input  uk-form-width-medium" type="text" placeholder="Выберите файл(ы)" disabled>
                    </div>
                </div>
                <div class="uk-margin">
                    <h4>Клиент</h4>
                    <hr>
                    <label for="firstname" class="uk-form-label">Имя</label>
                    <div class="uk-form-controls">
                        <input id="firstname" type="text" name="firstname" class="uk-input uk-form-width-large" value="{{ $item->client->firstname }}"><br>
                    </div>
                    <label for="surname" class="uk-form-label">Фамилия</label>
                    <div class="uk-form-controls">
                        <input id="surname" type="text" name="surname" class="uk-input uk-form-width-large" value="{{ $item->client->surname }}"><br>
                    </div>
                    <label for="phone" class="uk-form-label">Телефон</label>
                    <div class="uk-form-controls">
                        <input id="phone" type="text" name="phone" class="uk-input uk-form-width-large" value="{{ $item->client->phone }}"><br>
                    </div>
                    <div hidden>
                        <input type="number" name="client" value="1"><br>
                    </div>
                </div>
                <div class="uk-margin">
                    <h4>Сотрудник</h4>
                    <hr>
                    <label for="employee" class="uk-form-label">Сотрудник:</label>
                    <div class="uk-form-controls">
                        <select id="employee" class="uk-select uk-form-width-large" name="employee">
                            <option selected disabled>Выберите сотрудника</option>
                            @foreach($employees as $employee)
                                <option value="{{$employee->id}}" {{ $item->employee_id == $employee->id ? 'selected' : '' }}>{{ $employee->firstname . ' ' . $employee->surname }}  </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="uk-margin">
                    <button type="submit" class="uk-button uk-button-primary uk-width-1-1 uk-margin-small-bottom">Сохранить</button>
                </div>
            </form>
        </div>
    </section>
@endsection