routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resources([
    'recalls' => 'RecallController',
    'bids' => 'BidController'
]);

// menu
Route::get('/', 'SiteController@index')->name('index');
Route::get('/bids', 'BidController@index')->name('bids');
Route::get('/recalls', 'RecallController@index')->name('recalls');
Route::get('/jobs', 'JobController@index')->name('job');
Route::get('/contacts', 'ContactController@index')->name('contacts');
Route::get('/items/{item}', 'ItemController@show')->name('item_show');

Route::get('recalls/create', 'RecallController@create');


/**************************************************************************************************/

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout');

//Если нужно разрешить регистрацию других пользователей, тогда нужно ввести флаг для роли админа
Route::any('register', function (){
    return redirect('/');
});


Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function ()
{
    Route::post('items/{item}', 'ItemController@recovery')->name('item_recovery');

    Route::resources([
        'items' => 'ItemController',
        'employees' => 'HumanController',
        'recalls' => 'RecallController'
    ]);

// menu admin
    Route::get('/','SiteController@index');
    Route::get('/bids', 'BidController@index');
    Route::get('/recalls', 'RecallController@index');
    Route::get('/jobs', 'JobController@index');
    Route::get('/contacts', 'ContactController@index');
    Route::get('/emloyees','HumanController@index');
/**************************************************************************************************/

// Item
    Route::get('items/create','ItemController@create');
    Route::get('items/{item}/edit','ItemController@edit');
    Route::put('items/{item}','ItemController@update');
    Route::delete('items/{item}','ItemController@destroy')->name('item_delete');
/**************************************************************************************************/

// Employee
    Route::get('emloyees/create','HumanController@create');
    Route::get('emloyees/{emloyee}/edit','HumanController@edit');
    Route::put('emloyees/{emloyee}','HumanController@update');
    Route::delete('emloyees/{emloyee}','HumanController@destroy');
/**************************************************************************************************/
    // Recall
    Route::get('recalls/create', 'RecallController@create');
    Route::get('recalls/{recall}/edit','RecallController@edit');
    Route::put('recalls/{recall}','RecallController@update');
    Route::delete('recalls/{recall}','RecallController@destroy');

    // Bids
    Route::get('bids/{bid}/edit','BidController@edit');
    Route::put('bids/{bid}','BidController@update');

});

app/Recall.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recall extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/RecallController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Recall;

class RecallController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $recalls = Recall::orderBy('recalls.created_at', 'desc')->get();
        return view('recalls.index', compact('recalls'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('recalls.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'firstname' => 'required|string',
            'surname' => 'required|string',
            'email' => 'nullable|email',
            'recall' => 'required'
        ]);

        Recall::create([
            'firstname' => $request->get('firstname'),
            'surname' => $request->get('surname'),
            'email' => $request->get('email'),
            'recall' => $request->get('recall')
        ]);

        return redirect('recalls')->with('message', 'Отзыв добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $recall = Recall::find($id);
        return view('recalls.edit', compact('recall'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'firstname' => 'required|string',
            'surname' => 'required|string',
            'email' => 'nullable|email',
            'recall' => 'required'
        ]);

        $recall = Recall::find($id);

        $recall->firstname = $request->firstname;
        $recall->surname = $request->surname;
        $recall->email = $request->email;
        $recall->recall = $request->recall;

        $recall->save();

        return redirect('recalls')->with('message', 'Редактирование успешно сохранено!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $recall = Recall::find($id);
        $recall -> delete();
        return redirect('recalls')->with('message', 'Отзыв удален!');
    }
}

resources/views/recalls/create.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.message')
    <section uk-height-viewport="expand: true">
        <form action="{{ route('recalls.store') }}" method="POST" class="uk-form-horizontal uk-margin-large uk-inline">
            @csrf
            <div class="uk-margin uk-position-center">
                <h4>Форма отзыва</h4>
                <hr>
                <div class="uk-margin">
                    <label for="firstname" class="uk-form-label">Имя</label>
                    <div class="uk-form-controls">
                        <input id="firstname" type="text" name="firstname" class="uk-input uk-form-width-large"><br>
                    </div>
                </div>
                <div class="uk-margin">
                    <label for="surname" class="uk-form-label">Фамилия</label>
                    <div class="uk-form-controls">
                        <input id="surname" type="text" name="surname" class="uk-input uk-form-width-large"><br>
                    </div>
                </div>
                <div class="uk-margin">
                    <label for="recall_email" class="uk-form-label">Email</label>
                    <div class="uk-form-controls">
                        <input id="recall_email" type="text" name="email" class="uk-input uk-form-width-large"><br>
                    </div>
                </div>
                <div class="uk-margin">
                    <label for="recall" class="uk-form-label">Ваш отзыв</label>
                    <div class="uk-form-controls">
                        <textarea id="recall" name="recall" class="uk-textarea uk-form-width-large" rows="5" maxlength="1000" placeholder="Отзыв"></textarea>
                    </div>
                </div>
                <div class="uk-margin">
                    <button type="submit" class="uk-button uk-button-primary uk-width-1-1 uk-margin-small-bottom">Добавить</button>
                </div>
            </div>
        </form>
    </section>
@endsection

resources/views/recalls/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="uk-section">
        @include('layouts.message')
        <form action="{{ route('recalls.update', $recall->id) }}" method="POST" class="uk-form-horizontal uk-margin-large">
            @csrf
            @method('PUT')
            <div class="uk-margin">
                <h4>Отзыв</h4>
                <hr>
                <label for="firstname" class="uk-form-label">Имя</label>
                <div class="uk-form-controls">
                    <input id="firstname" type="text" name="firstname" class="uk-input uk-form-width-large" value="{{ $recall->firstname }}"><br>
                </div>
                <label for="surname" class="uk-form-label">Фамилия</label>
                <div class="uk-form-controls">
                    <input id="surname" type="text" name="surname" class="uk-input uk-form-width-large" value="{{ $recall->surname }}"><br>
                </div>
                <label for="email" class="uk-form-label">Email</label>
                <div class="uk-form-controls">
                    <input id="email" type="text" name="email" class="uk-input uk-form-width-large" value="{{ $recall->email }}"><br>
                </div>
                <div class="uk-margin">
                    <label for="recall" class="uk-form-label">Ваш отзыв</label>
                    <div class="uk-form-controls">
                        <textarea id="recall" name="recall" class="uk-textarea uk-form-width-large" rows="5" maxlength="1000">{{ $recall->recall }}</textarea>
                    </div>
                </div>
                <div class="uk-margin">
                    <button type="submit" class="uk-button uk-button-primary uk-width-1-1 uk-margin-small-bottom">Сохранить</button>
                </div>
            </div>
        </form>
    </section>
@endsection

resources/views/recalls/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="uk-section">
        @include('layouts.message')
        <div class="uk-margin uk-flex uk-flex-right">
            <a class="uk-button uk-button-primary uk-button-large uk-margin-small-top" href="{{url('recalls/create')}}">&#43; Добавить</a>
        </div>
        <h2>Отзывы</h2>
        <hr>
        <div class="uk-margin">
            @foreach($recalls as $recall)
                <div class="uk-margin">
                    <h4>{{ $recall->firstname }}&#32;{{ $recall->surname }}</h4>
                    <textarea class="uk-textarea uk-form-width" rows="5" maxlength="1000">{{ $recall->recall }}</textarea>
                    @if(Auth::check())
                        <div class="uk-margin uk-flex uk-flex-right">
                            <a class="blue" href="{{URL::to('recalls/'.$recall->id).'/edit'}}" title="Редактировать" uk-icon="pencil"></a>
                            <form action="{{ route('recalls.destroy', $recall->id) }}" method="POST" class="uk-form-horizontal" >
                                @csrf
                                {{method_field('DELETE')}}
                                <a href="" class="red uk-margin-small-left" title="Удалить" uk-icon="trash"></a>
                            </form>
                        </div>
                    @endif
                    <hr>
                </div>
            @endforeach
        </div>
    </section>
@endsection